### ISSUE TITLE
Could a demo application be provided?

### ISSUE THREAD

**Issue by chrispratt-tonyyeb** [saileshmittal/phonegap-system-notification-plugin#2]
Hi

I am quite new to phonegap / android development and would really appreciate an example / demo application to help understand how the code works and how best to implement it.

Thanks very much

**Comment by saileshmittal** [comment]
Hi,

  You can find the quick start guide here:
http://www.phonegap.com/start

**Comment by chrispratt-tonyyeb** [comment]
Hi, sorry I should have been more clear. I'm happily playing with phonegap but I wanted a demo application to show how to use your plugin for notification bar interaction.

Thanks

**Comment by saileshmittal** [comment]
Its been a really long time since I last used phonegap or even coded for android. I am working on iOS these days (no phonegap :) ). And the related code is lost somewhere in my disk :S.
But try to follow the steps in the README. If you stumble on anything, then I may be able to help you.
Sorry for not being of much help there. I'll look for the code and if I find it, will share.
